const menuButton=document.querySelector('.menu-button');
const nav=document.querySelector('.main-nav');
menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');}));
const references=['Adalya Artside Hotel','Adalya Elite Lara','Adalya Ocean Deluxe','Adalya Resort & Spa','Akdeniz Park AVM','Alanyum Alışveriş Merkezi','Alara Hotel','Alara Kum Hotel','Alara Park Hotel','Alara Star Hotel','Azura Deluxe Resort Hotel','Beach Club Doğanay','Blue Star Hotel','Bolu Koru Hotel','Bucak HES','Burak Turizm Gıda Deposu','Calido Maris Hotel','Calido Sol Hotel','Club Aqua Plaza','Club Kastalia Hotel','Club Paradiso Resort','Club Sun Heaven Hotel','Diamond Hill Resort Hotel','Drita Resort & Spa Hotel','Febeach Hotel','First Class Hotel','Galeri Resort','Grand Kaptan Hotel','Green Garden Resort & Spa','HRS Ankara Kadın Hastanesi','İncekum Orman Kampı','Klas Hotel','Klas Hotel Dom','Klas More Beach Hotel','Klas Turizm','Konaktepe Hotel','Lionel Hotel','Long Beach Alanya','Long Beach Club Nature Didim','Lonicera Resort & Spa Hotel','LRS Lake & River Side Hotel','LRS Port River Hotel','Luna Blanca Resort & Spa','Mary Palace Resort & Spa','May Garden Club Hotel','Modern Saraylar Hotel','Mukarnas Spa Resort','Numa Beach & Spa','Numa Exclusive Hotel','Numa Port Hotel','Özel Koru Hastanesi','Özel Meddem Hastanesi','Palmeras Beach Hotel','Port Side Resort Hotel','Ramira City Hotel','Ramira Hotel','Seabird Beach Hotel','Sensitive Premium Resort','Side Aquamarin Resort Hotel','Side Crown Charm Hotel','Side Crown Palace','Side Crown Serenity','Side Crown Sunshine Hotel','Side La Grande Resort & Spa','Sirius Deluxe Hotel','Sunprime C-Lounge Hotel','Sunstar Beach Hotel','Sunstar Resort Hotel','SVS Otelcilik','Taç Premier Hotel','Tu Casa Gelidonya Hotel','Villa Side Hotel','Villa Side Residence','White City Beach Hotel','White City Resort','Wome Deluxe Hotel','Xeno Club Mare Hotel','Xeno Eftalia Resort','Xeno Sonas Alpina Hotel','Yalıhan Aspendos Hotel','Yalıhan Una Hotel'];
const referenceLogos={'Adalya Artside Hotel':'adalya.svg','Adalya Elite Lara':'adalya.svg','Adalya Ocean Deluxe':'adalya.svg','Adalya Resort & Spa':'adalya.svg','Akdeniz Park AVM':'akdeniz-park.webp','Azura Deluxe Resort Hotel':'azura.svg','Club Kastalia Hotel':'kastalia.svg','Club Paradiso Resort':'paradiso.webp','Galeri Resort':'galeri.svg','Green Garden Resort & Spa':'green-garden.png','Klas Hotel':'klas.png','Klas Hotel Dom':'klas.png','Klas More Beach Hotel':'klas.png','Klas Turizm':'klas.png','Lonicera Resort & Spa Hotel':'lonicera.png','Mukarnas Spa Resort':'mukarnas.png','Numa Beach & Spa':'numa.png','Numa Exclusive Hotel':'numa.png','Numa Port Hotel':'numa.png','Özel Koru Hastanesi':'koru.webp','Özel Meddem Hastanesi':'meddem.png','Wome Deluxe Hotel':'wome.svg'};
const referencesGrid=document.querySelector('#references-grid');
if(referencesGrid){referencesGrid.innerHTML=references.map(name=>{const initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toLocaleUpperCase('tr-TR');const logo=referenceLogos[name];return `<article class="reference-card reveal">${logo?`<img src="${logo}" alt="" loading="lazy">`:`<span class="reference-monogram" aria-hidden="true">${initials}</span>`}<h3>${name}</h3></article>`}).join('');}
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(reduced){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));}else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
